### ISSUE TITLE
3.4.0 extension issue .

### ISSUE THREAD

**Issue by apps4u** [codenvy/sdk#53]
Hi Ive been runing 3.2.0 and Ive installed your sample plugins and I move to 3.4.0 last night I cleaned and rebuilt codenvy-sdk and I copied the hello-world plugin to the ext folder and when I tried to run extInstall.sh it would not build I would get e error saying that the pom file in the `assembly-sdk/target/tomcat-id/sdk-resource/temp/pom/xml`  was incorrect . I tracked it down on line 291 of the pom file in the temp folder. what would happen when running extInstall the maven build adds the extension in the ext folder as a dependancy to the pom file but what was happening it was placing the dependancy in the tag like this 

```
   </de         <dependency>
            <artifactId>wizard-api-tutorial</artifactId>
            <groupId>com.codenvy.plugin-sdk</groupId>
            <version>1.5.0-SNAPSHOT</version>
        </dependency>pendencies>
```

as you can see it not going between the tags but into the tag. Once I switched back to version 3.2.0 I can build in extensions but using 3.4.0 I get this error no matter which extension I try to install. 
Thanks for your time.

**Comment by apps4u** [comment]
Has anyone had this same issue, I still can not seem to be able to run any extension wether mine or one of the samples shipped with the SDK I still have the pom file error. :)

**Comment by paulvi** [comment]
try public group forums or email as mentioned at https://codenvy.com/technical-support/

**Comment by JamesDrummond** [comment]
Please feel free to reopen this issue.
